### ISSUE TITLE
Validate before update in component?

### ISSUE THREAD

**Issue by bryanbuchs** [maoberlehner/vuex-map-fields#108]
I'm trying to validate input (w/ vuelidate) and need to stop a commit from happening if it fails.  I see where I can write a custom mutation, but that doesn't have access to the validation object I need. 

Is there component-level access to override the computed get/set methods?

**Comment by geoidesic** [comment]
You can pass whatever you want into a mutation as a parameter. I'm not sure what you mean by `component-level access`. The examples show how you can build your own custom mutation.

**Comment by geoidesic** [comment]
Closing this as there's been no further feedback from the OP
