### ISSUE TITLE
how to user vuex-map-fields with cdn ?

### ISSUE THREAD

**Issue by silvesterwali** [maoberlehner/vuex-map-fields#110]
hi...  i new to use vue . first sorry for my english may not good so far...#ask so i working with vue and vuex with cdn..im working with multipe form input with two data binding so i want to make every v-model get value or data from vuex.but i have problem how to update every object inside the vuex state 
im find the solution to use vuex-map-fields with cdn https://www.jsdelivr.com/package/npm/vuex-map-fields
and when i read the docs  i get this
![image](https://user-images.githubusercontent.com/40487188/85520728-e170a800-b635-11ea-9ccc-e486bb9ec5b7.png)
so how i  import or using it on my cdn vue

**Comment by maoberlehner** [comment]
Hello! I answered this here: https://github.com/maoberlehner/vuex-map-fields/issues/89
Hope that works. Thanks!

**Comment by silvesterwali** [comment]
this so helped terima kasih ... @maoberlehner
