### ISSUE TITLE
Using vuedraggable "Computed property "simpleSetForms" was assigned to but it has no setter."

### ISSUE THREAD

**Issue by SaulMoonves** [maoberlehner/vuex-map-fields#120]
I am attempting to use vuedraggable to create draggable form snippets inside an vuex array named simpleSetForms, using vuex-map-fields via:

...mapMultiRowFields(['simpleSetForms']),

and when I drag the form sections to change their order in the array, I receive the error: Using vuedraggable "Computed property "simpleSetForms" was assigned to but it has no setter."

Can vuex-map-fields provide a generic setter that it seems vuedraggable expects? I tried to do this myself but failed.

**Comment by geoidesic** [comment]
Hi @SaulMoonves 
I'm not really sure what you mean. Perhaps you could create a codesandbox link that highlights the issue you are facing?

`mapFields` does create a getter and setter on the mapped vuex value, to an alias on the root scope of the vm on which the mapping was made.

From what I can make out from your description, it sounds like it should work.

**Comment by geoidesic** [comment]
Closing due to lack of feedback from OP
