### ISSUE TITLE
[vuex] unknown mutation type: real_state/updateField

### ISSUE THREAD

**Issue by GarciaTandela** [maoberlehner/vuex-map-fields#121]
Hi i'm using the Vuex store with a input with v-model, whenever i try to change the value it returns me this message in the console.log, and the state in Vuex store doesn't change

**Comment by geoidesic** [comment]
@YannickSilva 
As described in the README, you have to create the `updateField` on mutation on your store. 
https://github.com/maoberlehner/vuex-map-fields#store
