### ISSUE TITLE
Multiple getterTypes 

### ISSUE THREAD

**Issue by jurgenbosch** [maoberlehner/vuex-map-fields#18]
Hi,

I'm working Vuex modules to state my data. 
I store the data in multiple modules to keep my code base nice and clean. 

When using vuex-map-fields I have a situation where I'm using data from multiple modules. 
There seems to be no method to do this or I am doing it wrong. 

Below is my current code; 
**My component**
```
<template>
    <div class="">
        <input type="text" v-model="no_panels"><br>
        <input type="text" v-model="firstName"><br>
        <router-link to="/step-2">Go to step 2</router-link>
    </div>
</template>

<script>
    import { createHelpers } from 'vuex-map-fields';

    const { mapFields } = createHelpers({
        getterType: [
            'getKitchenField',
            'getApplicantField',
        ],
        mutationType: 'updateKitchenField',
    });

    export default {
        computed: {
            ...mapFields(['no_panels', 'firstName', 'lastName'])
        },
    }
</script>
```

**My store file**
```
import kitchen from './kitchen';
import applicant from "./applicant";

export default {
    modules: {
        kitchen: kitchen,
        applicant: applicant
    },
    strict: false
}
```

**Applicant.js**
```
import { createHelpers } from 'vuex-map-fields';

const { getApplicantField, updateApplicantField } = createHelpers({
    getterType: 'getApplicantField',
    mutationType: 'updateApplicantField',
});

export default {
    state: {
        firstName: '',
        lastName: ''
    },
    getters: {
        getApplicantField
    },
    mutations: {
        updateApplicantField
    }
}
```

The code above results in the following error:
>Error in render: "TypeError: this.$store.getters[getterType] is not a function"

**Comment by maoberlehner** [comment]
Hey @jurgenbosch,

you're almost there, but instead of passing multiple getters to `createHelpers()`, you can destructure and rename the return value of `createHelpers()` and call it twice.

```js
const { mapFields: mapKitchenFields } = createHelpers({
  getterType: 'getKitchenField',
  mutationType: 'updateKitchenField',
});
const { mapFields: mapApplicantFields } = createHelpers({
  getterType: 'getApplicantField',
  mutationType: 'updateApplicantField',
});

export default {
  computed: {
    ...mapKitchenFields(['no_panels']),
    ...mapApplicantFields(['firstName', 'lastName']),
  },
}
```

**Comment by jurgenbosch** [comment]
Awesome! Thank you. Never thought of the destructor. I guess I was stuck at the array option ;)

**Comment by jurgenbosch** [comment]
One more question .. 

Is there a way to use module_name.store_name syntax in the template? 
In the current setup it might happen that both modules contain a store for the title. 

In the current situation I can only use it once.

**Comment by maoberlehner** [comment]
You can rename properties: https://github.com/maoberlehner/vuex-map-fields#rename-properties

**Comment by jurgenbosch** [comment]
I've seen that solution but and I imagined prefixing everything but that doesn't feel like a nice solution because it would basically adding more work to rename all fields and makes it unnecessary complicated. 

It tried something like; 
```
export default {
        computed: {
            ...mapKitchenFields({
                kitchen: {
                    no_panels: 'no_panels',
                    plintm2: 'plintm2'
                }
            }),
            ...mapApplicantFields(['firstName', 'lastName'])
        },
    }
```
But this results in a error saying;
> "TypeError: path.split is not a function"

Ideal would be to have something like:
```
const { mapFields: mapApplicantFields, prefix: 'applicant' } = createHelpers({
        getterType: 'getApplicantField',
        mutationType: 'updateApplicantField',
    });
```

And then use 'applicant.firstName' in the template instead of just 'firstName'.

**Comment by maoberlehner** [comment]
I think that's a pretty good Idea – I'm open for pull requests. See: https://github.com/maoberlehner/vuex-map-fields/issues/19

**Comment by maoberlehner** [comment]
I might work on it myself the following days, but I can't guarantee that I have time.

**Comment by abhinukala** [comment]
Hi @maoberlehner What if I have to use all the fields in the state more than once i.e using it in multiple components. How do I handle this situation?

For Example, 

const { mapFields: mapKitchenFields } = createHelpers({
  getterType: 'getKitchenField',
  mutationType: 'updateKitchenField',
});
const { mapFields: mapApplicantFields } = createHelpers({
  getterType: 'getApplicantField',
  mutationType: 'updateApplicantField',
});

export default {
  computed: {
    ...mapKitchenFields(['no_panels', 'firstName', 'lastName']),
    ...mapApplicantFields(['no_panels','firstName', 'lastName']),
  },
}

In this case, there is no point in creating two constants when they have the same fields. If I am using it in more than two time I have to create more constants and repeat the existing code which I don't want to. It would be helpful if you can provide an example how to handle this.

**Comment by maoberlehner** [comment]
Hey @abhinukala Your example would not work, because the fields mapped with `mapKitchenFields` and `mapApplicantFields` have the same names. You'd have to [rename the fields](https://github.com/maoberlehner/vuex-map-fields#rename-properties).

If you don't want to write the `createHelpers()` function multiple times with the same parameters, you could create a file like this:

```js
// src/store/map-applicant-fields.js
export const { mapFields: mapApplicantFields } = createHelpers({
  getterType: 'getApplicantField',
  mutationType: 'updateApplicantField',
});
```

```js
// in your component...
import { mapApplicantFields } from '../store/map-applicant-fields.js';

// ...
```

Or if you're using Vuex modules and assuming you have an `applicant` Vuex module you could use the module file to provide the `mapFields` helper function:

```js
// src/store/modules/applicant.js

export const applicant = {
  state: {
  // ...
  },
  // ...
};

export const { mapFields: mapApplicantFields } = createHelpers({
  getterType: 'getApplicantField',
  mutationType: 'updateApplicantField',
});
```

I'm not quite sure tough if I understood your problem correctly, please provide more informations if I got it wrong :)

Thx.

**Comment by abhinukala** [comment]
@maoberlehner. Thank you for your response. Let me put my question this way. I have an address component(which has line1, line2, city, state and zip fields) that will be reused in multiple other components like Title and Registration as a sub-component. Now when I fill the address in Title.vue, in my store I need to have this information saved in the state -> title object. Save for registration.  So basically I need to differentiate where the address is coming from. Hope this makes my question clear.

**Comment by maoberlehner** [comment]
I wrote an [article about reusable Vuex modules](https://markus.oberlehner.net/blog/how-to-structure-a-complex-vuex-store/). In the article you can see, that the `contact.js` and `address.js` Vuex modules are reused. Is this close to what you want to achieve?

**Comment by geoidesic** [comment]
Closing this as there has been no further feedback from @abhinukala
