### ISSUE TITLE
String formatting of the getterType and mutationType arguments to createHelpers

### ISSUE THREAD

**Issue by savandriy** [maoberlehner/vuex-map-fields#21]
I tried to do stuff like:
```javascript 
const {mapFields} = createHelpers({getterType: `${nsName}/getField`, mutationType: `${nsName}/updateField`});
```
But it didn't work. I pass "nsName" as props. I want to create reusable components.
Do you think there's a way to achieve this kind of behavior?

Thanks in advance!

**Comment by maoberlehner** [comment]
Hey @savandriy!

I'm not quite sure if I understand correctly what you want to achieve?

```js
// This should work!
const nsName = 'someString';
const {mapFields} = createHelpers({getterType: `${nsName}/getField`, mutationType: `${nsName}/updateField`});
```

**Comment by savandriy** [comment]
I want to receive "nsName" in props. 

```
<script>
  import {createHelpers} from 'vuex-map-fields';

 const {mapFields} = createHelpers({getterType: `${nsName}/getField`, mutationType: `${nsName}/updateField`'});

  export default {
    name: 'DataTableComponent',
    props: ["nsName"],
    computed: {
      ...mapFields([
        'searchResults',
      ])
    }
  }
</script>
```
Maybe there's a way to create the helpers on a lifecycle hook or something?

**Comment by maoberlehner** [comment]
This is not possible. You can't access the props of a Vue.js component from outside the component.

```html
<script>
  import {createHelpers} from 'vuex-map-fields';

 // This is outside of the Vue.js component object, you don't have access to any props or data of the component. `nsName` is `undefined` here.
 const {mapFields} = createHelpers({getterType: `${nsName}/getField`, mutationType: `${nsName}/updateField`'});

  export default {
    // Inside this block you have access to the props via `this.propName` (e.g. `this.nsName`).
    name: 'DataTableComponent',
    props: ["nsName"],
    computed: {
      ...mapFields([
        'searchResults',
      ])
    }
  }
</script>
```

**Comment by savandriy** [comment]
Ah, now I see.
In that case, can I call 
```createHelpers({getterType: `${nsName}/getField`, mutationType: `${nsName}/updateField`'})```
inside the export default block?
maybe right inside the computed?

**Comment by maoberlehner** [comment]
Theoretically you can do that, but practically you can't use the helpers created that way. There is now way (I'm aware of) how you can pass helpers created *inside* the component / at the time the component is created, to the computed properties of the same component. Sorry.

**Comment by savandriy** [comment]
Anyway, thanks!

**Comment by maoberlehner** [comment]
I'm closing this because there is nothing more to do. Thank you for contributing.
