### ISSUE TITLE
Nested Properties not working

### ISSUE THREAD

**Issue by hanxue** [maoberlehner/vuex-map-fields#22]
In my `store.js`, I have a couple of modules, and a few nested properties in one of the module

```js
const moduleProjectDetails = {
  state: {
    infrastructureClass: '',
    publicServiceClass: '',
    projectUnit: {
      ton: '',
      square_cubic_meter: '',
      kilometer: '',
      mu: '',
    },
  },
  getters: {
    getField,
  },
  mutations: {
    updateField,
  },
}

export default new Vuex.Store({
  modules: {
    basicInput: moduleBasicInput,
    projectDetails: moduleProjectDetails,
  },
})
```

In my `Component.vue`, I use mapfields, and call the property with the identifier after the last `.`

```html
<md-input class="" v-model="infrastructureClass"></md-input>
<md-input class="" v-model="publicServiceClass"></md-input>
<md-input class="" v-model="ton"></md-input>
<md-input class="" v-model="square_cubic_meter"></md-input>
<md-input class="" v-model="kilometer"></md-input>
<md-input class="" v-model="mu"></md-input>

<script>
import Vue from 'vue'
import { mapFields } from 'vuex-map-fields'

export default {
  name: 'ProjectDetails',
  computed: {
    ...mapFields([
      'infrastructureClass',
      'publicServiceClass',
      'projectUnit.ton',
      'projectUnit.square_cubic_meter',
      'projectUnit.kilometer',
      'projectUnit.mu',
    ]),
  },
}
</script>
```

I see this error message:

```
[Vue warn]: Error in render: "TypeError: Cannot read property 'ton' of undefined"

found in

---> <ProjectDetails> at src/components/ProjectDetails.vue
       <MdTab> at src/components/MdTabs/MdTab.vue
         <MdContent> at src/components/MdContent/MdContent.vue
           <MdTabs> at src/components/MdTabs/MdTabs.vue
             <App> at src/MainScreen.vue
               <MdContent> at src/components/MdContent/MdContent.vue
                 <MdAppContent> at src/components/MdApp/MdAppContent.vue
                   <MdAppInternalSideDrawer> at src/components/MdApp/MdAppSideDrawer.vue
                     <App> at src/App.vue
                       <Root>
```

I see the nested properties available in the Vue.js devtools

![image](https://user-images.githubusercontent.com/760008/40027198-666ed5a8-580b-11e8-8e8a-2e453827559f.png)

How can I properly access the nested properties?

### Environment

Node: v9.11.1
Vue: 2.5.2
vuex-map-fields: 1.1.7

**Comment by abhinukala** [comment]
+1 I have the same issue. I have multiple nested objects 
state: {
   title: {
     titleNum: '',
     ownerName: '',
     dealerName:'',
     vehicleYear:'',
     address: {
         line1:'',
         line2: '',
         city: '',
         adrState: '',
         zip:''
     }
   },
   getters: {
    getField,
  },
  mutations: {
    updateField,
  }
}

In my component 

<m-title label="Title No" name="title"  v-model="titleNum" ></m-title>
<m-text name="ownerName" label= "Owner Name"  v-model="ownerName"></m-text>
<m-text name="dealerName" label= "Agent Name"  v-model="dealerName"></m-text>
<m-numeric name="vehicleYear" label= "Vehicle Year"  v-model="vehicleYear"></m-numeric>
<m-address></m-address>

<script>
    export default {
    computed: {
        ...mapFields([
            'titleNum',
            'ownerName',
            'dealerName',
            'vehicleYear',
            'address.line1',
            'address.line2',
            'address.city',
            'address.adrState',
            'address.zip'
        ])
    },
</script>

I see the error
[Vue warn]: Error in render: "TypeError: Cannot read property 'line1' of undefined"

I have passed props to the address component 
<m-address :address="$store.state.title.address"></m-address>
This resolved the above error but the store wont update with the values entered in the component.

Any help on this issue would be greatly appreciated.

**Comment by hanxue** [comment]
This is how `moduleBasicInput` looks like

```javascript
const moduleBasicInput = {
  state: {
    investmentCapital: '4.90',
    capitalRatio: '20',
    financingRatio: '40',
    loanInterestRate: '4.9',
    formulaType: 'article21',
    valueType: 'constant',
    discountRate: '3.3',
    profitMargin: '6.5',
    corporateIncomeTax: '25',
    bankRepaymentMode: 'EqualAmountPrincipal', // EqualCapitalAndInterest
    governmentEquity: '10',
    capitalGains: '',
  },
  getters: {
    getField,
  },
  mutations: {
    updateField,
  },
}
```

**Comment by hanxue** [comment]
I mange to solve it by copying the syntax for the examples before looking at your reply

```javascript
import { createHelpers } from 'vuex-map-fields'

const { mapFields } = createHelpers({
  getterType: 'constructionInvestment/getField',
  mutationType: 'constructionInvestment/updateField',
});

export default {
  name: 'ConstructionInvestment',
  computed: {
    ...mapFields([
      'constructionCost_amount',
      'constructionCost_percentage',
    // ...
```

Thanks so much for explaining in detail in your answer, and a 👍 for the excellent documentation

**Comment by arimourao** [comment]
I'm developing a app using Nuxtjs and I'm using namespaced store and I'm getting this exact problem of property undefined when trying to access a nested property. This is the relevant portion of my code:

**Store**
_getters.js_

```
import {getField} from 'vuex-map-fields'

export default {
  getProductField(state) {
    return getField(state)
  }
}

```
_```
mutations.js_
```
import {updateField} from 'vuex-map-fields'

export default {
  UPDATE_PRODUCTS_FIELD(state, field) {
    updateField(state, field)
  }
}

```

_component_
```
const {mapFields} = createHelpers({
  getterType: `products/getProductField`,
  mutationType: `products/UPDATE_PRODUCTS_FIELD`
})
```


Worth of notice, I'm getting this problem right after I'm resetting all properties of the object in the state that vuex-map-fields is mapping. I'm calling this mutation.
```
CLEAR_PRODUCT(state) {
    const product = {
      id: null,
      title: null,
      status: 'active',
      price: null,
      pictures: [],
      description: null,
      tags: [],
      cost: null,
      virtual_available_quantity: null,
      available_quantity: null,
      manufactoring_time: null,
      dimensions: {
        height: null,
        length: null,
        width: null,
        weight: null
      },
      variations: [],
      variationsInfo: {
        attributeTags1: [],
        attributeTags2: [],
        attributeTags3: [],
        attributeName1: '',
        attributeName2: '',
        attributeName3: ''
      }
    }

    Vue.set(state, 'product', product)
  },

```
And I'm getting undefined exactly in the first nested object, that is dimensions.height. I'm using in the component like this:

```
computed: {
   ...mapFields([
      'product.id',
      'product.title',
      'product.status',
      'product.price',
      'product.pictures',
      'product.description',
      'product.tags',
      'product.cost',
      'product.virtual_available_quantity',
      'product.available_quantity',
      'product.manufactoring_time',
      'product.variations',
      'product.variationsInfo.attributeName1',
      'product.variationsInfo.attributeName2',
      'product.variationsInfo.attributeName3',
      'product.dimensions.height',
      'product.dimensions.length',
      'product.dimensions.width',
      'product.dimensions.weight'
    ]),
```

and then in the input

     
```
<input
      v-model="height"
       type="number"
       name="altura"
        style="width: 5rem;"
 />
```


Am I missing something? Any help would be much appreciated!
