### ISSUE TITLE
mapMultiRowFields does something strange with an array?

### ISSUE THREAD

**Issue by driekus77** [maoberlehner/vuex-map-fields#27]
Hi All,

I liked how-to-structure-a-complex-vuex-store a lot and I'm trying to use the idea's. 

Unfortunately it looks like my "vue-tables-2": "^1.4.50" is not working fine together with mapMultiRowFields from "vuex-map-fields": "^1.2.3".

It looks to come down to the code in my form:
```
      ...mapUsersFields({
        users: 'rows',
        selectedSeqno: 'selectedSeqno',
        currentPage: 'currentPage',
      }),

      ...mapUsersMultiRowFields(
        { multiUsers: 'rows' }
      ),
```
users is working fine inside the vue-tables-2 but multiUsers is not. v-for..loop on multiUsers is working perfect so it could be that it's a problem with the table. 
But I don't know what to say to the vue-tables-2 team what mapUsersMultiRowFields does? Can you elaborate a little bit? In the debugger I noticed something like reactiveGetter & reactiveSetter being added. Is this all there is?

My users.js store code (partly):
```
export const { mapFields: mapUsersFields } = createHelpers({
	getterType: 'admin/users/getField',
	mutationType: 'admin/users/UpdateField'
});

export const { mapMultiRowFields: mapUsersMultiRowFields } = createHelpers({
	getterType: 'admin/users/GetField',
	mutationType: 'admin/users/UpdateField'
});
```

The captial GetField is called in the debugger and seems to be working fine.

Hopefully you can point me in the right direction for a solution.

Kind regards,
Henry

**Comment by maoberlehner** [comment]
Hi @driekus77 it would be great if you could provide a [reduced test case](https://css-tricks.com/reduced-test-cases/) to demonstrate the problem. Ideally on https://jsfiddle.net/

Thanks!

**Comment by driekus77** [comment]
Hi @maoberlehner ,

Took me some time to figure jsfiddle out: https://jsfiddle.net/y5w72x87/33/

If you switch in the computed part:
```
  computed: {
        ...mapTodoFields({
        todos: 'todos',
      }),

      ...mapTodoMultiRowFields(
        { mtodos: 'todos' }
      )
  },
```

mapTodoFields ==> todos and mapTodoMultiRowFields ==> mtodos 👍 
mapTodoFields ==>ptodos and mapTodoMultiRowFields ==> todos 👎  

Thanks for any help and/or feedback!

Kind regards,
Henry

**Comment by driekus77** [comment]
Oke man thanks for looking into it!
