### ISSUE TITLE
Is it possible to make this synchronous?

### ISSUE THREAD

**Issue by kajeagentspi** [maoberlehner/vuex-map-fields#34]

**Comment by maoberlehner** [comment]
Hey @kajeagentspi, can you provide more details? I'm not quite sure what you mean? 🤔

vuex-map-fields is purely synchronous, but there are some parts of Vuex and Vue.js which are async. Vuex actions are async and `v-model` updates in Vue.js are async. There is no way around that.

**Comment by kajeagentspi** [comment]
Ahh thanks for the clarification. 👍
