### ISSUE TITLE
Why mapMultiRowFields returns empty objects?

### ISSUE THREAD

**Issue by RVeligotskiy** [maoberlehner/vuex-map-fields#35]
https://jsfiddle.net/roman1101/te4ordgh

**Comment by RVeligotskiy** [comment]
Thank you. I had warn Cannot read property 'name' of undefined when i define data like that:
var all = []
all[1] = {id:1, name:'name1'}
all[2] = {id:3, name:'name1'}
...
state:{all},
...

But this is Vue feature

**Comment by geoidesic** [comment]
@RVeligotskiy can you please show the data definition that did work? So that we can see the difference.

**Comment by geoidesic** [comment]
@maoberlehner If you create a separate independent computed value that points to `chacteristic` then that reference to the store will not render empty.

See here for example of this based on above example: https://jsfiddle.net/noeldacosta/o1ae65nd/7/

This suggests that this is a reactivity issue. This is highlighted by the buttons I've added. If you view the inspector you will see that the aliased computed property is an observer whereas the other is not.

**Comment by conor-odro** [comment]
Is there any further updates on this? This is still an issue in June 2021.

A workaround for now is to use the store directly, but it doesn't _feel_ like the correct solution.

```js
this.$store.state.characteristics
```
