### ISSUE TITLE
Slow performance alongside Logger plugin

### ISSUE THREAD

**Issue by Harti** [maoberlehner/vuex-map-fields#39]
This may or may not be completely unrelated to this library - however it only started occurring once I added the `mapFields` function to my component.
I added [Vuex's Logger plugin](https://vuex.vuejs.org/guide/plugins.html#built-in-logger-plugin) to my Vuex store shortly before I found this (awesome!) lib. 

When I then started to type in a v-model input field with the value being mapped by the library, the application started to lag dramatically: Typing five letters took the application one minute to update the component:

```
mutation note/updateField @ 10:53:56.285
mutation note/updateField @ 10:54:05.071
mutation note/updateField @ 10:54:16.510
mutation note/updateField @ 10:54:26.158
mutation note/updateField @ 10:54:35.493
```

In comparison, without the Logger, it takes less than 100ms.

This is not a big deal, I simply disabled Logger and it seems I'm good now.
Just wanted to let you know that Logger doesn't seem to like vuex-map-fields very much 😛

**Comment by maoberlehner** [comment]
Hey @Harti,

that's interesting, thanks for the info. Because I'll likely make some major changes under the hood in the next major release anyway, and because I don't think this is a major issue, I'll most likely not fix that.

But thank you for letting me know!
