### ISSUE TITLE
How to make mapping with html textarea?

### ISSUE THREAD

**Issue by AndrianD** [maoberlehner/vuex-map-fields#46]
Hello,
Nice plugin, thank you . However how can I make two way data-binding with a `<textarea></textarea>` ?

Thank you for your answer.

**Comment by anikolaev** [comment]
@AndrianD It works the same way as with any other field: https://codesandbox.io/s/o764zxq76y

**Comment by maoberlehner** [comment]
Thanks @anikolaev for helping out!
