### ISSUE TITLE
Map multi row fields inside of multi row fields

### ISSUE THREAD

**Issue by cory-weiner** [maoberlehner/vuex-map-fields#47]
I have an interesting use case that I'm not sure is possible with vuex map fields.

Assuming a state that looks like so:
```
shipment: {
    id: 1,
    addresses: [
        {zip: 1000, state: 'NE', residents: [
            {name:'Jim', age:27},
            {name:'Ann', age:30}
        ]},
        {zip: 1000, state: 'NE', residents: [
            {name:'Sue', age:27},
            {name:'Betty', age:30}
        ]},
    ]
}

```
 
You can use mapMultiRowFields to map the addresses. However, how would you handle the array of residents inside of the array? Trying to access the resident.name throws a mutation error when in vuex strict mode. Is it possible to mutate a nested array inside of array with 2 way binding?

**Comment by maoberlehner** [comment]
Hey @cory-weiner,

unfortunately this is currently not possible with `vuex-map-fields`.

Because I want to keep this package as minimal as possible, I'm also not planning to add this feature anytime soon. Sorry.
