### ISSUE TITLE
Nested Properties with Multiple Levels

### ISSUE THREAD

**Issue by nmf2** [maoberlehner/vuex-map-fields#49]
Hello, @maoberlehner

First of all, thank you for this project, it has really helped me!

But I believe I've found a bug in it, basically it doesn't work with nested properties which have more than one level. Like so:

```
propA: {
  propB: {
    propC: "something"
  }
}
```

If I try to use something like:

`mapFields(['propA.propB.propC'])`

I get an error saying that I can't access propC of undefined.

**Comment by Adrek** [comment]
I have same error. When I access to propA level is correct. but when I access level Prop B o C appears this error:
"Property or method "formInfo" is not defined on the instance"
