### ISSUE TITLE
how to use mapMultiRowFields on nested state ?

### ISSUE THREAD

**Issue by blackinitial** [maoberlehner/vuex-map-fields#50]
i use nuxt js, i want to implementation dynamic form like https://markus.oberlehner.net/blog/how-to-handle-multi-row-forms-with-vue-vuex-and-vuex-map-fields/
how to access mapMultiRowFields on nested state store, `bookingData.flight.passengers` ?
and i got error `store.getters[getterType] is not a function`

store/bookingData.js
```js
import { getField, updateField } from 'vuex-map-fields'

export const state = () => ({
  flight: {
    contact: {
      title: '',
      fullname: '',
      email: '',
      phone: ''
    },

    passengers: [
      {
        title: '',
        fullname: '',
        birthday: ''
      },
      ...
    ]
  }
})

export const getters = { getField }

export const mutations = {
  updateField
}
```

component.vue
```js
<template>
.card.shadow.mb-4(v-for="passenger, index in passengers" v-on:key="'passengers'+index")
  input.form-control(
    type="text" required
    v-model="passenger.fullname")
.....

<script>
.....
computed: {
  ...mapMultiRowFields({ passengers: 'bookingData.flight.passengers' })
}
.....

```

**Comment by maoberlehner** [comment]
Hey @blackinitial!

Am I right that `bookingData` is a namespaced module? If so, this should help: https://codesandbox.io/s/2v042zjw0r

You can read more about dealing with namespaced modules here: https://github.com/maoberlehner/vuex-map-fields#namespaced-vuex-modules

**Comment by wingsico** [comment]
I solve it with:
```js
import { createHelpers } from 'vuex-map-fields'
import { mapMutations } from 'vuex'
const { mapFields, mapMultiRowFields } = createHelpers({
  getterType: 'my_module/getField',
  mutationType: 'my_module/updateField',
})

export default {
  // ...
  computed: {
    ...mapMultiRowFields(['address']),
  },
  // ...
}
```

I think it will be helpful for you!

**Comment by geoidesic** [comment]
Closing this due to no further feedback from OP.

**Comment by lasteuropean** [comment]
> Hey @blackinitial!
> 
> Am I right that `bookingData` is a namespaced module? If so, this should help: https://codesandbox.io/s/2v042zjw0r
> 
> You can read more about dealing with namespaced modules here: https://github.com/maoberlehner/vuex-map-fields#namespaced-vuex-modules

I'm struggling with this exact issue; the difference is that I'm using Nuxt.js and am having trouble implementing this part:

`const store = new Vuex.Store({
  // ...
  modules: { bookingData }
});`

Any advice? Also get this message in my developer console when I use mapMultiRowFields 
"(error during evaluation)"
