### ISSUE TITLE
updateField doesn't support broken paths

### ISSUE THREAD

**Issue by fusionbeam** [maoberlehner/vuex-map-fields#52]
I have to map an object with a two level depth of nested dynamic properties.
i.e. myContainer.$category.$name.value

I am calling commit('updateField', {path:`myContainer.${category}.${name}`, value:metric.value});
If $category has never been set separately this break with an error 'Cannot set property ... of null'.

This should be an easy fix, to ensure path safety by creating empty objects if the key doesn't exist already.

**Comment by maoberlehner** [comment]
Hey @fusionbeam! This seems to be the same as https://github.com/maoberlehner/vuex-map-fields/issues/41 (I know, the title is a bit misleading I guess)

Pull requests are welcome!

I'll close this issue, please use https://github.com/maoberlehner/vuex-map-fields/issues/41 for further discussion of the topic.

Please let me know if I miss understood your problem and I'll reopen this. Thanks!

**Comment by fusionbeam** [comment]
@maoberlehner technically this is different but I can see how working on a fix for #41 can include a fix for this use case as well.
I'm working on a pull request.
