### ISSUE TITLE
mapMultiRowFields for nested arrays inside array

### ISSUE THREAD

**Issue by luchorengo** [maoberlehner/vuex-map-fields#55]
The context of my use case is a store module for a customer object. A customer has many phones, many addresses and many contacts. Each contact has many phones and many addresses besides other basic info.
The structure of my module state is like:

```
state: {
        details: {},
        phones: [],
        addresses: [],
        contacts: [
            {
                first_name: '',
                last_name: '',
                phones:[],
                addresses: []
            }
        ]
    },
```

Everything is working fine for the first array level: phones, addresses and contacts are mapped correctly.
Is possible to map the arrays inside the contacts array? I thought that doing something like this would work, but I'm getting `Cannot read property 'map' of undefined"` error.

`...mapMultiRowFields('customer', { phones: "contacts.phones" }),`

Thanks in advance

**Comment by junyo** [comment]
+1

**Comment by maoberlehner** [comment]
Unfortunately, this is currently not possible. I want to keep this package as simple as possible so I don't have any plans adding this feature. Although, if somebody finds a simple solution to this I'd consider accepting a pull request. Thx!

**Comment by alexsonnay** [comment]
+1 Did anyone find a solution ?
