### ISSUE TITLE
github dependency not supported

### ISSUE THREAD

**Issue by fusionbeam** [maoberlehner/vuex-map-fields#56]
Current project configuration doesn't support GitHub dependencies.

Referring to it from another project package.json dependencies (i.e. "vuex-map-fields": "git://github.com/fusionbeam/vuex-map-fields#master") doesn't work. Results in a dependency not found vuex-map-fields build error.

**Comment by maoberlehner** [comment]
This is not a priority for me. Thx for reporting.

**Comment by fusionbeam** [comment]
@maoberlehner I did some research and all is needed here is to add ```"prepare": "yarn build"``` to package.json ```scripts``` section.
