### ISSUE TITLE
Use the simple method with Nuxt.js?

### ISSUE THREAD

**Issue by mehrunrasoli** [maoberlehner/vuex-map-fields#57]
Hey @maoberlehner.
I've been using computed set&get to enable the two-way binding for vuex states but seems using the [Basic example](https://github.com/maoberlehner/vuex-map-fields#basic-example) with this module is a really cleaner way!

however, I'm not sure how to implement this on my Nuxt.js project where every model has its own Store.
Tried to do the same way as basic example but I get this error:
```javascript
TypeError: this.$store.getters[getterType] is not a function
```

I [searched for it on the closed issues](https://github.com/maoberlehner/vuex-map-fields/issues?utf8=%E2%9C%93&q=is%3Aissue+this.%24store.getters%5BgetterType%5D+is+not+a+function) but didn't find the answer I'm looking for.

![Screenshot from 2019-03-11 16-50-09](https://user-images.githubusercontent.com/7046255/54126873-ca487f80-441d-11e9-861f-537fc7655d60.png)

**Comment by maoberlehner** [comment]
Hey @mehrunrasoli!

Nuxt uses namespaced Vuex modules by default: https://github.com/maoberlehner/vuex-map-fields#namespaced-vuex-modules

So if you have a file `store/user.js` than the namespace is `user`

```js
export default {
  computed: {
    ...mapFields('user', ['name']),
  },
};
```

**Comment by mehrunrasoli** [comment]
WOW! it's now amazing!!
I going to try it soon.
Thank You!

**Comment by renattonl** [comment]
Hey @maoberlehner  Your answer has not helped me. When I reload the page I get:

![Captura de pantalla de 2019-03-20 16-38-59](https://user-images.githubusercontent.com/6575723/54721066-058a3300-4b2f-11e9-9811-c4f1d628bd95.png)

Help me!
