### ISSUE TITLE
[Question] How to call mapped mutation outside component

### ISSUE THREAD

**Issue by deka** [maoberlehner/vuex-map-fields#58]
Hi,
Is it possible to call mapped mutation outside vue component ?

**Comment by maoberlehner** [comment]
Hello!

You can call the `updateField` mutation like a regular mutation from everywhere. But you can't use `mapFields()` outside of a component. Does this answer your question?

**Comment by deka** [comment]
I do not see the syntax to use
i have a namespaced module 'myModule', with a mapped state property 'prop' .

Something like ? 
```
store.commit('myModule/updateField', {  prop : 'newValue' }) 
```

**Comment by maoberlehner** [comment]
Almost:

```js
store.commit('myModule/updateField', {  path: 'prop', value: 'newValue' });
```

The path is basically whats `user.firstName` or `user.lastName` is in this example: https://github.com/maoberlehner/vuex-map-fields#component-1

**Comment by deka** [comment]
Thx. :satisfied:
With a chapter in the doc it will be top 
:beers:
