### ISSUE TITLE
[Vue warn]: Error in render: "TypeError: this.$store.getters[getterType] is not a function"

### ISSUE THREAD

**Issue by marianagarciaferreira** [maoberlehner/vuex-map-fields#59]
I'm trying to use more I always get this error

![Captura de Tela 2019-03-27 às 08 55 30](https://user-images.githubusercontent.com/36300077/55074098-2510e680-506e-11e9-9a0f-3fe3dfb02085.png)

**Comment by maoberlehner** [comment]
Thank you for taking the time creating an issue. Please provide a [reduced test case](https://github.com/maoberlehner/vuex-map-fields/blob/master/CONTRIBUTING.md#reporting-issues) for the bug. You can clone one of the CodeSandboxes linked in the README to do so. Thanks

**Comment by geh18** [comment]
@marianagarciaferreira You might be using **namespaced: true**. Try including the name of the namespace in your mapFields function.

`...mapFields([
        'login/phone',
      ]),
`

**Comment by maoberlehner** [comment]
Closing this because inactivity of the initiator.

Thx @geh18. That's very likely to be the problem.

**Comment by geoidesic** [comment]
In the docs it says that you can do this for namespaces modules:
```
...mapFields([ 'login/phone', ]),
```
but the problem is that you end up with a computed property called `login/phone` instead of just `phone`.

**Comment by plweil** [comment]
I know this is late to the game, but I just ran into this issue and this thread pinpointed the problem. But then there is the v-model issue mentioned by @geoidesic. To get around it, you can map the field to a different name; e.g.;

``...mapFields( 'login', {
    phoneLogin: 'phone'
    }),
    ``

**Comment by vladfr** [comment]
This happens because you didn't wire your state module correctly. You need to add `getField` and `updateField` to your getter and mutation types.

```
import { getField, updateField } from 'vuex-map-fields'

export default {
  namespaced: true,
  state,
  getters: { ...getters, getField },
  mutations: { ...mutations, updateField },
  actions
}
```
