### ISSUE TITLE
Exposing multiple fields on complex object

### ISSUE THREAD

**Issue by grount** [maoberlehner/vuex-map-fields#60]
First of all thanks for your contributions, it is a great utility!

I am using Vuex with non namespaced modules.
I have a complex object that I would like to bind to a form, for example:

```javascript

const { getStructureField, updateStructureField } = createHelpers({
  getterType: 'getStructureField',
  mutationType: 'updateStructureField',
});

const moduleA = {
  state = {
    structure: {
      sectionA: {
        name: 'Section A',
        key1: {
          title: '1 input',
          value: '1 value',
        },
        key2: {
          title: '2 input',
          value: '2 value',
        },
        key3: {
          title: '3 input',
          value: '3 value',
        },
        key4: {
          title: '4 input',
          value: '4 value',
        }
      }
    }
  },
  mutations: { updateStructureField },
  getters: { getStructureField }
}
```
I want to bind the content of the key1...keyX to fields in my component.
I thought about exposing the structure field and then accessing it by structure.sectionA.key1.title, etc.. but it didn't work

```javascript
<template>
  <Section :title="structure.sectionA.name"/>
</template>

<script>
import { createHelpers } from 'vuex-map-fields';

const { mapFields } = createHelpers({
  getterType: 'getStructureField',
  mutationType: 'updateStructureField',
});

export default {
  name: 'ComponentName',
  computed: {
    ...mapFields(['structure']),
  },
};
</script>
```

Am I missing something? If so maybe we can try to re-write the documentation, I found it a bit difficult to understand.
Also, found #9 does it mean it is not supported?

**Comment by maoberlehner** [comment]
Hello @grount!

As far as I can see, this should work. Can you create a reproduction link on CodeSandbox? (you can fork one of the examples in the documentation to get started) Thx!

**Comment by geoidesic** [comment]
Closing this as no further feedback from OP
