### ISSUE TITLE
How create new instance of component(array in form) without repeat values in store?

### ISSUE THREAD

**Issue by mensonones** [maoberlehner/vuex-map-fields#61]
I have form and inside his contains other component(indicators) based in object in store with vue-map-fields, but, i have create this component form with component(indicators) in new tab, but values in input in indicators equals form already filled.

**Comment by maoberlehner** [comment]
Did you already read this article https://markus.oberlehner.net/blog/how-to-handle-multi-row-forms-with-vue-vuex-and-vuex-map-fields/ ?

Otherwise I need more informations. CodeSandbox link would be appreciated.

**Comment by mensonones** [comment]
Yes, I Read. In my case, i reuse component that contains form and component based in object in store. I would like to know how I can create a new instance of this form without repeating the values already entered in a new form. This new form does not lie in another component of tab.
