### ISSUE TITLE
Unable to bind on array specific index

### ISSUE THREAD

**Issue by fabien-michel** [maoberlehner/vuex-map-fields#64]
Hi,
Trying to use mapFields with an index of array (something like `addresses[0]` ) is not working.
The bind is simply doesn't made whereas it work with a nested value. `addresses[0].town`

```
computed: {
    ...mapFields({
      town: "addresses[0].town", // ok
      addresse: "addresses[0]", // not ok
      addresses: "addresses" // ok
    })
  }
```
Sandbox demo of the issue:
https://codesandbox.io/embed/vuex-map-fields-nested-properties-06fb7

**Comment by maoberlehner** [comment]
That's not possible with this package. But you can use `mapState` if you only want to read `addresses[0]`.

**Comment by marceloavf** [comment]
Even something like `addresses[0].town[0]` is not possible @maoberlehner ?

**Comment by maoberlehner** [comment]
No. That's what `mapMultiRowFields` is for if it fits your use case.
