### ISSUE TITLE
I have a question about data binding in vuex (on initialized)

### ISSUE THREAD

**Issue by pasudo123** [maoberlehner/vuex-map-fields#66]
- The component A is a dialog, which uses mapFields.

After changing the state value of vuex, we initialized the specific state value of vuex when the dialog is subsequently closed.

However, the v-model data in the mapfield of the dialog has not been initialized.

When viewed with vue devtool, the state value has been initialized but the value visible in the dialog has not been initialized.

I want to undo the value of vuex. However, the value on the dialog has the value before closing.

```javascript
computed: {
    ...mapGetters(['isDialog', 'iSelectedRuleData']),
    ...mapFields({
        ruleName: 'iSelectedRuleData.ruleName',
        ruleDesc: 'iSelectedRuleData.ruleDesc',
    }),

```
this mutation code 
```javascript
state.iSelectedRuleData.ruleName = '';
state.iSelectedRuleData.ruleDesc = '';
```

```javascript
<v-text-field v-model="ruleName" required></v-text-field>
```

**Thank you for making a useful open source.**

**Comment by maoberlehner** [comment]
Hi! I think you have to mutate the root property `iSelectedRuleData` in your mutation.

```js
state.iSelectedRuleData = { ...state.iSelectedRuleData, ruleName: '', ruleDesc: '' };
```

**Comment by pasudo123** [comment]
Sadly, it is not initialized.

__This code is called when the dialog is closed.__
```javascript
this.initISelectedRuleData();
```

__This code is internal to the method.__
```javascript
initISelectedRuleData(state) {

    console.debug('vuex init : initISelectedRuleData');

    state.iSelectedRuleData = {
        ...state.iSelectedRuleData,
        ruleName : '',
        ruleDesc : '',
    };

   /// 
```

Is this because the data remains in the V-TextField as a payload?

I do not know..

**Comment by maoberlehner** [comment]
> Something seems to have been a problem.
> I tried again and it is resetting !!

That's great! :)
So can we close this?

**Comment by pasudo123** [comment]
yes 👍
