### ISSUE TITLE
How to handle array fields in store?

### ISSUE THREAD

**Issue by dab** [maoberlehner/vuex-map-fields#7]
Hello there. Please help me to understand how to handle array fields with this plugin. I have `members` array in store.
It's easy to map array itself with

```js
computed: {
      ...mapFields([
        'org.members'
      ])
    },
```

adding new items to the array dynamically with needed fields, like:

```js
    methods: {
      addMember: function(e) {
        e.preventDefault();
        this.$store.state.org.members.push(Vue.util.extend({}, {
          name: '',
          email: ''
        }))
      }
    }
```

and dynamically showing this data in template with:

```html
        <section
          v-for="member in members"
          :key="member.name"
        >
          <input placeholder="Name" v-model="member.name"
          ></input>
          <input placeholder="Email" v-model="member.email"
          ></input>
        </section>
```

But it's not working, store is not updating.
Thanks for help.

**Comment by maoberlehner** [comment]
Thanks for reporting this issue. I'll look into this the following days.

**Comment by maoberlehner** [comment]
Ok, I figured it out – it is a little hacky I guess, but it works:

## Component HTML

Note that I changed the `:key`, if you're using the `name` of the member, updating the name will re-render!

```html
<template>
  <div>
    <section
      v-for="(member, index) in members"
      :key="member.id"
    >
      <input placeholder="Name" v-model="self[`member${index}name`]">
      <input placeholder="Email" v-model="self[`member${index}email`]">
    </section>
  </div>
</template>
```

## Component JS

```js
// src/components/DemoComponent.vue
import { mapState } from 'vuex';
import { mapFields } from 'vuex-map-fields';

import { store } from '../store';

const fieldMapping = store.state.members.reduce((prev, _, index) => {
  prev[`member${index}name`] = `members[${index}].name`;
  prev[`member${index}email`] = `members[${index}].email`;

  return prev;
}, {});

export default {
  computed: {
    // This is a "little" hacky...
    self() {
      return this;
    },
    ...mapState(['members']),
    ...mapFields(fieldMapping),
  },
};
```

## Store

```js
// src/store.js
import Vue from 'vue';
import Vuex from 'vuex';

import { getField, updateField } from 'vuex-map-fields';

Vue.use(Vuex);

export const store = new Vuex.Store({
  getters: {
    getField,
  },
  mutations: {
    updateField,
  },
  state: {
    members: [
      {
        id: 1,
        name: 'name 1',
        email: 'email 1',
      },
      {
        id: 2,
        name: 'name 2',
        email: 'email 2',
      },
    ],
  },
});
```

**Comment by dab** [comment]
Thanks! I will check it.

**Comment by maoberlehner** [comment]
Hey @dab!

I looked further into this and realized, that my approach is not working when a new `member` is dynamically added. I'm currently working on adding the functionality needed to deal with such situations with dynamically added fields. I'll release a new version to next days!

**Comment by maoberlehner** [comment]
A new function was added for such use cases: https://github.com/maoberlehner/vuex-map-fields#multi-row-fields

**Comment by jmsuresh** [comment]
> A new function was added for such use cases: https://github.com/maoberlehner/vuex-map-fields#multi-row-fields

In my case, I want to map an Object and access property by key value. Please consider adding this feature. Thanks.

**Comment by vladislavGovoritov** [comment]
How to handle array(with primitives) fields? - ["one", "two "]

**Comment by vladislavGovoritov** [comment]
<div v-for="(item, index) of addInfo" :key="index">
      <v-text-field
        label="test"
        v-model="addInfo[index]"
      ></v-text-field>
    </div>
