### ISSUE TITLE
How to use map-fields with module decorators?

### ISSUE THREAD

**Issue by AndeeZee** [maoberlehner/vuex-map-fields#71]
Hello!
I want to use vuex-map-fields with vuex-module-decorators: https://github.com/championswimmer/vuex-module-decorators.
However, due to the different syntax, I'm currently lost, how to set it up for a dynamic namespaced module.
Any help is appreciated.
Kind regards,
Andy

**Comment by maoberlehner** [comment]
Hello! Unfortunately I don't have any experience with that. But maybe somebody else can help you.

**Comment by rainux** [comment]
I also experienced the same issue, I found we can create our own getter and mutation to wrap `getField` and `updatedField` provided by `vuex-map-fields`:

```ts
import { Module, Mutation, VuexModule } from 'vuex-module-decorators'
import { getField, updateField } from 'vuex-map-fields'

import store from '@/store'

@Module({
  namespaced: true,
  name: 'MyModule',
  dynamic: true,
  store,
})
export default class MyModule extends VuexModule {
  get getField() {
    return getField(this)
  }

  @Mutation
  updateField(options: {path: string; value: any}) {
    return updateField(this, options)
  }
}
```

**Comment by geoidesic** [comment]
@AndeeZee Does rainux's solution solve your problem?

**Comment by AndeeZee** [comment]
Hello!
Yes, this helped a lot and sorry for not coming back earlier.
I'll close this issue now.
Andy
