### ISSUE TITLE
Why does mapMultiRowFields exist?

### ISSUE THREAD

**Issue by AlexSHoffman** [maoberlehner/vuex-map-fields#72]
The docs don't really explain what's the difference between `mapFields` and `mapMultiRowFields`. And the following code from the example page works exactly the same with both of these, so what's the difference?

## Using `mapFields`

```JS
<template>
  <div id="app">
    <div v-for="address in addresses">
      <label>ZIP <input v-model="address.zip"></label> {{address.zip}}<br>
      <label>Town <input v-model="address.town"></label> {{address.town}}
      <hr>
    </div>
  </div>
</template>

<script>
import { mapFields } from "vuex-map-fields";

export default {
  name: "App",
  computed: {
    ...mapFields(["addresses"])
  }
};
</script>
```

## Using `mapMultiRowFields`

```JS
<template>
  <div id="app">
    <div v-for="address in addresses">
      <label>ZIP <input v-model="address.zip"></label> {{address.zip}}<br>
      <label>Town <input v-model="address.town"></label> {{address.town}}
      <hr>
    </div>
  </div>
</template>

<script>
import { mapMultiRowFields } from "vuex-map-fields";

export default {
  name: "App",
  computed: {
    ...mapMultiRowFields(["addresses"])
  }
};
</script>
```

Does `mapMultiRowFields` allow you to commit mutations of nested properties and `mapFields` 
 does not? e.g.:

```JS
computed: {
  ...mapMultiRowFields(["addresses"])
}

this.addresses.zip = 'newValue'
```
or what's the difference?

**Comment by maoberlehner** [comment]
> If you want to build a form which allows the user to enter **multiple rows** of a specific data type with multiple fields (e.g. **multiple addresses**) you can use the multi-row field mapping function.

But now that you say it, I definitely agree that the text in the readme doesn't do a great job of explaining it and neither does the example code.

This article explains it in detail: https://markus.oberlehner.net/blog/how-to-handle-multi-row-forms-with-vue-vuex-and-vuex-map-fields/

**Comment by AlexSHoffman** [comment]
@maoberlehner thanks for the link and for creating this module in general, it's quite nice!
