### ISSUE TITLE
debouncing updateField when using mapMultiRowFields (or any other)

### ISSUE THREAD

**Issue by add1ct3dd** [maoberlehner/vuex-map-fields#73]
Hi,

I'm using the plugin currently with great success, but as we get to more complex forms I'm finding myself wanting to debounce the store events so we reduce the commits and subsequent actions, but cannot currently see a way to do this.

I already have a store.subscribe which listens to the specific store module updating, by checking for mutation type 'some/store/module/updateField', which is fine, but I'd like to debounce them for longer user input, or constant user input.

Generally debouncing via lodash requires it to be done on the input side, rather than the store side, so I don't want to do this in the store.subscribe, but I'm wondering if this is something you have considered for updateField, and if not if it could be?

Thanks!

**Comment by maoberlehner** [comment]
Hello,

I thought about this but for me it never was a problem.
You can also use the `.lazy` modifier https://vuejs.org/v2/guide/forms.html#lazy if you're concerned about performance.
I want to keep the code of this package as minimal as possible so there won't be debouncing built in any time soon. Sorry.
