### ISSUE TITLE
Question: How to push an item into an array

### ISSUE THREAD

**Issue by OuZuYu** [maoberlehner/vuex-map-fields#74]
Such as this example
https://codesandbox.io/embed/vue-template-zthyf

When I push an object it will error

**Comment by maoberlehner** [comment]
You have to push directly into `addresses` and not overwrite `addresses`.

See: https://markus.oberlehner.net/blog/how-to-handle-multi-row-forms-with-vue-vuex-and-vuex-map-fields/
