### ISSUE TITLE
Nested properties

### ISSUE THREAD

**Issue by MLDMoritz** [maoberlehner/vuex-map-fields#79]
Hey there,

Imagine following structure:

```js
{
    name: null,
    address: {
        street: null,
        number: null,
        ...
    }
}
```

The address is passed to another Component, like `<AddressForm :form="address" />` and accesses its sub-properties.

I think currently it's not possible to do that. I tried several ways but the output is not what I would expect:

```
  computed: {
    test() {
      return mapFields('user/create-corporation', [
        'form.postalAddress.country',
        'form.postalAddress.locality',
        'form.postalAddress.postalCode',
        'form.postalAddress.streetAddress'
      ])
    },
```
returns `{ "country": {}, "locality": {}, "postalCode": {}, "streetAddress": {} } `

```
test: {
      ...mapFields('user/create-corporation', [
        'form.postalAddress.country',
        'form.postalAddress.locality',
        'form.postalAddress.postalCode',
        'form.postalAddress.streetAddress'
      ])
    },
```

returns nothing.

Is there any workaround or something that I am missing out? Thanks!

**Comment by hackel** [comment]
mapFields generates helper functions for each field.  You need to put it directly in computed.  Is `'user/create-corporation'` really the name of your vuex module?  Maybe read through the documentation again.  This really isn't the right place to go for support.
```
  computed: {
    ...mapFields('user/create-corporation', [
        'form.postalAddress.country',
        'form.postalAddress.locality',
        'form.postalAddress.postalCode',
        'form.postalAddress.streetAddress'
    ]),
  }
```
`this.country` will set/return the value of `$this.store.state['user/create-corporation'].form.postalAddress.country`

**Comment by MLDMoritz** [comment]
It works that way, the problem on my side is that I have 2 address objects. If I manipulate that nested object it mutates the store directly without using the helper functions.

`this.form.address.country = 'DE'` results in that error.

**Comment by geoidesic** [comment]
Hi. Firstly I think you may have the wrong path to you field. Your shown data structure does not show a `form` node, nor a `postAddress` node. 

If you want to manipulate the stored data then you must use `this.$store.commit('updateField',{someDataStructureHere})`. However if you get your structure and model names mapped correctly then you shouldn't need to do that manipulation explicitly. 

Maybe best if you create a codesandbox to demonstrate your case.

**Comment by geoidesic** [comment]
Closing this as there has been no further feedback from @MLDMoritz
