### ISSUE TITLE
Changing attribute on nested object throws mutation error.

### ISSUE THREAD

**Issue by HunterHillegas** [maoberlehner/vuex-map-fields#80]
Hi,

Great utility. I'm new to Vue but it's saving me a ton of code. I am struggling with one aspect and I can't tell if I'm hitting an edge case or what.

Taking this example:

https://codesandbox.io/embed/vuex-map-fields-multi-row-fields-113i4?fontsize=14&hidenavigation=1&theme=dark

I've extended the address multi-row example so that the addresses include an object with a couple of parameters to handle favoriting, etc... I've bound the attributes to checkboxes. This contrived example is similar to what I'm hitting in my own app.

The problem is that while it renders correctly, when I attempt to mutate it (i.e. toggle a checkbox), I get a stern error that I'm mutating state directly. I'm not trying to do that intentionally, I swear! :-)

Do the wrappers that vuex-map-fields creates not extend to those types of properties? Do I need to use a different syntax? Any help appreciated.

Cheers!

**Comment by maoberlehner** [comment]
Hi!

In you example, `address` is a regular object. So when you change `address.zip` via `v-model` you indeed mutate the state directly.

`vuex-map-fields` can only detect changes to `address` directly. It is not intended to be used the way you do in your example. Sorry.

Take a look at https://davestewart.github.io/vuex-pathify/#/ maybe this works better for your use case.
