### ISSUE TITLE
 [Vue warn]: Computed property was assigned to but it has no setter.

### ISSUE THREAD

**Issue by kms-rscholz** [maoberlehner/vuex-map-fields#81]
For some reason, I get the following error when using `mapMultiRowFields`:

```
vue.runtime.esm.js?2b0e:619 [Vue warn]: Computed property "entries" was assigned to but it has no setter.
```
Anything wrong with the following syntax?

```
<MilestonesList v-model="entries" :months="months" />
```

```
import { mapFields, mapMultiRowFields } from 'vuex-map-fields'

export default {
    computed: {
        ...mapMultiRowFields({
           entries: 'updated.brand.general_info.milestones.entries'
        })
    }
})
```

**Comment by kms-rscholz** [comment]
Same result for:

```
export default {
    computed: {
        ...mapMultiRowFields(['updated.brand.general_info.milestones.entries'])
    }
})
```

```

This workaround leads to an error in `MilestonesList`:
```
computed: {
    entries: {
      get() {
        return this.$store.state.updated.brand.general_info.milestones.entries
      },
      set(value) {
        this.$store.commit('updateField', {
          path: 'updated.brand.general_info.milestones.entries',
          value: value
        })
      }
    }
  }
```

**Comment by maoberlehner** [comment]
You can't use `v-model` on `entries`. When you want to use `mapMultiRowFields()` You must iterate over `entries` and use `v-model` on each `entry`.

See: https://github.com/maoberlehner/vuex-map-fields#component-5

**Comment by JLopeDeB** [comment]
Hi @maoberlehner, I came across the same issue while trying to use mapMultiRowFields on a Vuetify.js [ v-autocomplete with chips](https://vuetifyjs.com/en/components/autocompletes/#dense). Do you have any suggestion for that case? Thank you, the library is super useful.
