### ISSUE TITLE
v-model.lazy is acting the same way as regular v-model

### ISSUE THREAD

**Issue by marekkaczkowski** [maoberlehner/vuex-map-fields#83]
**Expected behavior**
`v-model.lazy` on input should trigger `updateField` on input blur.

**Current behavior**
`updateField` is triggered on every key-press; `lazy` modifier is ignored on `v-model`.

**Comment by maoberlehner** [comment]
I don't think that this is the case.

[Checkout this demo](https://codesandbox.io/s/94l98vx0p4) and change `v-model` to `v-model.lazy` it works as expected.

I think you are confusing this with `v-model.lazy` [not working on custom input components](https://github.com/vuejs/vue/issues/6914). This has nothing to do with this package.
