### ISSUE TITLE
Watching changes on mapMultiRowFields

### ISSUE THREAD

**Issue by Imboga** [maoberlehner/vuex-map-fields#86]
In my case scenario, I need to set a property based on another property. Let me explain it better:
I have an array of invoice details:
```
details: [
    {
        amount: null
        quantity: null
        product: {
            id: 1
            name: 'Lorem ipsum',
            price: 1234
        },
    },
    {
        amount: null
        quantity: null
        product: {
            id: 2
            name: 'Dolor at',
            price: 3456
        },
    },
]
```
My store module simply looks like
```
state: {
        details: [],
},
getters: {
        getField,
},
mutations: {
        updateField,
}
```
and my component is mapping in this way
```
...mapMultiRowFields('invoice', [
        'details',
]),
```
Question is: how can I set de `detail.amount` with the `detail.product.price` when the product is selected/changed? I need to use it as a suggested price but keep the `detail.amount` bound to the state since the user can manually change the value.
I was thinking to overwrite the `details` state mutations but not sure if it's doable and how can it be done.
Also, I've found a vuex-watcher plugin but not even sure if it will work

Any help/recommendations will be really appreciated.

**Comment by geoidesic** [comment]
The way I handled this is with an `@input` directive. You pass in the row index as a parameter, call the `updateField` mutation in the method, using the row index in your path, e.g. 
```
this.$store.commit('updateField', {path: `details[${index}].amount`, value: value})
```

**Comment by maoberlehner** [comment]
For more advanced use cases, you might consider to use https://davestewart.github.io/vuex-pathify/#/ instead of this package.

Otherwise, you can use the approach @geoidesic provided.
