### ISSUE TITLE
Committing to binded field

### ISSUE THREAD

**Issue by mrdigitalau** [maoberlehner/vuex-map-fields#96]
Hey there,

I have a bit of a weird one.

I have a form which is bound to my store using this plugin - it works awesome! Thank you.

The only thing I want to do is on mount, to automatically assign something to one of the form fields.

For example, I have a select field with options ['red','green','blue];
There is a v-model on this select field which is mapping my 'colour' field in my store.

I can't put the colour as default in my store, I need to query the database and get the default colour and somehow update the default colour on mount, in my mount function if I try to assign the dynamically retrieved colour - nothing happens. It also doesn't work when I try to do a mutation of that field.

Is there any other way, perhaps something I'm missing?

Cheers

**Comment by maoberlehner** [comment]
> Provide a reduced test case or a live example.

– https://github.com/maoberlehner/vuex-map-fields/blob/master/CONTRIBUTING.md#reporting-issues

**Comment by geoidesic** [comment]
@mrdigitalau Most likely this is a race condition that is causing the problem. I.e. you are probably doing the request and assignment asynchronously. You need to ensure that your assignment occurs only once your request has completed, in other words you need to look into Promise handling and / or async / await. 

I'm closing this as there is no further feedback from OP. If you still have an issue, please feel free to reply and I'll re-open it.
